name: Bug Report
description: File a bug report.
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
        
  - type: textarea
    attributes:
      label: Summary
      description: |
        A clear and concise description of the bug.

        Please include the full output from `uv run daydream-scope` with the complete error message.
    validations:
      required: true
      
  - type: input
    attributes:
      label: Platform
      description: What operating system and architecture (include system RAM) are you using?
      placeholder: e.g. macOS 14 arm64, Windows 11 x86_64, Ubuntu 20.04 amd64
    validations:
      required: true
      
  - type: input
    attributes:
      label: Nvidia GPU
      description: What Nvidia GPU are you using? (see `nvidia-smi --query-gpu=name,memory.total --format=csv,noheader`)
      placeholder: e.g. NVIDIA GeForce RTX 4090, 24564 MiB
    validations:
      required: true
      
  - type: input
    attributes:
      label: Scope Version
      description: What version of Scope are you using? (see `uv run daydream-scope --version`)
      placeholder: "e.g. daydream-scope: 0.1.0a1 git commit: 4baaaec"
    validations:
      required: true
      
  - type: input
    attributes:
      label: uv Version
      description: What version of `uv` are you using? (see `uv --version`)
      placeholder: e.g. uv 0.8.22
    validations:
      required: false
      
  - type: input
    attributes:
      label: node Version
      description: What version of `node` are you using? (see `node -v`)
      placeholder: e.g. v22.20.0
    validations:
      required: false
